### ISSUE TITLE
Create a PPA

### ISSUE THREAD

**Issue by deekayen** [deekayen/norman#1]
The instructions for the linux xorg file might be pointing to the wrong place for making a PPA. /usr/share/X11/xkb/symbols might be a more appropriate place, but the /etc place should still get tried.

**Comment by jdve** [comment]
It's made it into [xkeyboard][1]!  Thanks, Tilman!  And, of course, thanks @deekayen for an amazing layout!  I've now been happily using it for over a year with much better efficiency and physical comfort.

[1]: https://groups.google.com/a/listserv.bat.ru/d/msg/xkb/kKcSC83OerA/C2m5V2XafPwJ

**Comment by deekayen** [comment]
Closing this since it's in xkeyboard.
