### ISSUE TITLE
OSX Installers hang "Waiting for other installations to finish."

### ISSUE THREAD

**Issue by johnkershaw** [deekayen/norman#11]
Both installers (normal & challenge) lock up at the end with this message. I have to Force Quit the installers. Just me?

![image](https://cloud.githubusercontent.com/assets/5265410/19542925/090c103c-969d-11e6-98e9-fbe2415e7269.png)

**Comment by deekayen** [comment]
I just tried them on a fresh Sierra install and didn't have that problem.

**Comment by deekayen** [comment]
I uploaded a new installer today to finish #4.

**Comment by johnkershaw** [comment]
I can confirm that both installers now function correctly on my Mac (Yosemite).

The standard installer forces me to restart whilst the challenge installer doesn't. I can still access the installed layout(s) after either procedure, ie the restart is not necessary (I force quitted the Norman installer - restarts are only for system updates!)

**Comment by deekayen** [comment]
I didnt update the challenge installer.

**Comment by deekayen** [comment]
I just updated both installers. The regular one no longer requires restart. The challenge has the bugfix from #4 and a new icon.
