### ISSUE TITLE
OSX Login screen does not support norman

### ISSUE THREAD

**Issue by gerwinbrunner** [deekayen/norman#14]
Hi,

I'm trying out Norman for several days now and I like it a lot.
One strange thing happens thou. On the login screen of osx the Norman layout is not available and the system switches automatically to US.

Any idea why this happens?

Best,
Gerwin

**Comment by gerwinbrunner** [comment]
I just found the answer to my problem in the readme :)
https://github.com/deekayen/norman/blob/master/mac/README.md

**Comment by deekayen** [comment]
@gerwinbrunner Part of integrating the layout deeper in to MacOS is getting it added in more places elsewhere. https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/merge_requests/24 is a merge request I just opened to promote Norman to a full layout in xkeyboard-config, which would put it as a feature option in Chromebooks and Android. If you would go add helpful promotion links or just a thumbs up, that may help resolve this situation someday in MacOS.
