### ISSUE TITLE
Programmer Norman ?

### ISSUE THREAD

**Issue by alvinometric** [deekayen/norman#16]
Hi,

Thanks for creating this layout! I'm really tempted by it but I'm facing the same issue as colemak in finding a "programmer" alternative that inverts the number row so symbols are easier to reach.

I'm curious to know what your thoughts are on this, or if there is anyway that I could help, even though I've never done anything that low-level.

Thanks,
Alvin

**Comment by danielcompton** [comment]
See #12.

**Comment by deekayen** [comment]
https://github.com/stephenkeep/norman/tree/master/mac has a Norman-P layout, but no description on what exactly it is and no pull request back here.

**Comment by alvinsight** [comment]
Woaw, thanks a lot for the detailed instructions @handcoding ! 
That's really nicely explained, I'll give a go later, in the end I might stick with colemak because of the broader support, and the "the" issue doesn't bother me that much at the moment.
But, I still need my number row inverted, so this is super helpful!

**Comment by handcoding** [comment]
@alvinsight: Anytime—I’m happy to help!

**Comment by deekayen** [comment]
I started working on a norman-p bundle for mac tonight based on the work from @stephenkeep.

![norman-p v2](https://user-images.githubusercontent.com/382319/41630840-3394cbe6-73ff-11e8-84fa-652e8ed69436.png)
<img width="16" alt="norman-p" src="https://user-images.githubusercontent.com/382319/41630843-3678ab8e-73ff-11e8-831b-8265589ce9a8.png">

**Comment by deekayen** [comment]
Please review https://github.com/deekayen/norman/commit/28fdc7f67d6512df95218eb89a4ac4ec835c708b

**Comment by deekayen** [comment]
I tried to make it extra-easy: https://github.com/deekayen/norman/releases/tag/2.2.0

**Comment by deekayen** [comment]
I actually need feedback on the Norman-P I added for Mac in 2.2.0. @stephenkeep's proposal swaps the location of ' and ; so I want to have the discussion about how "P" that is.

**Comment by deekayen** [comment]
https://www.rei.com/media/36e5a520-df0b-40ea-bf31-6b6d67643ec8?size=120x90

**Comment by deekayen** [comment]
<img width="591" alt="norman-p_mac_keyboard" src="https://user-images.githubusercontent.com/382319/41886246-9287c9fe-78c9-11e8-94fd-9a31ca49d67a.png">

**Comment by yubaoquan** [comment]
I don'k think moving the `;` down is a good idea, because single quota button is also a frequently used button. So after shifting to norman-p, People made more mistakes on declaring string variables. Swapping `;` and `'` doesn't bring much convenience

**Comment by growtofill** [comment]
The square brackets not being swapped for curly brackets is a surprising disappointment (they are swapped in Workman-P). So many popular programming languages use curly brackets to create blocks (C, C++, Go, Java, JavaScript, Ruby).

**Comment by deekayen** [comment]
@growtofill  Great, that's exactly the sort of feedback I was looking for.

**Comment by deekayen** [comment]
@growtofill so are you saying in your comment revision that the [ should remain the base key to not break the shortcuts and NOT match the workman-p swap?
