### ISSUE TITLE
loadkeys compatible file

### ISSUE THREAD

**Issue by ALTinners** [deekayen/norman#23]
I've made a `loadkeys` compatible file for my personal use on Arch and our company servers when in the Linux VT and X keyboard mappings aren't available - would this be wanted for the repository? 

I can't say I know what I'm doing here - there is a lot of verbosity I skipped over for lack of "not knowing what it was for". But it works...so yeah

On my Arch machine - this goes in `/usr/share/kbd/keymaps/i386/qwerty/norman.map.gz` - might be different for different distros

```
keycode  16 = +q
	shift keycode  16 = +Q
keycode  17 = +w
	shift keycode  17 = +W
keycode  18 = +d
	shift keycode  18 = +D
keycode  19 = +f
	shift keycode  19 = +F
keycode  20 = +k
	shift keycode  20 = +K
keycode  21 = +j
	shift keycode  21 = +J
keycode  22 = +u
	shift keycode  22 = +U
keycode  23 = +r
	shift keycode  23 = +R
keycode  24 = +l
	shift keycode  24 = +L
keycode  25 = semicolon        colon
keycode  30 = +a
	shift keycode  30 = +A
keycode  31 = +s
	shift keycode  31 = +S
keycode  32 = +e
	shift keycode  32 = +E
keycode  33 = +t
	shift keycode  33 = +T
keycode  34 = +g
	shift keycode  34 = +G
keycode  35 = +y
	shift keycode  35 = +Y
keycode  36 = +n
	shift keycode  36 = +N
keycode  37 = +i
	shift keycode  37 = +I
keycode  38 = +o
	shift keycode  38 = +O
keycode  39 = +h
	shift keycode  39 = +H
keycode  44 = +z
	shift keycode  44 = +Z
keycode  45 = +x
	shift keycode  45 = +X
keycode  46 = +c
	shift keycode  46 = +C
keycode  47 = +v
	shift keycode  47 = +V
keycode  48 = +b
	shift keycode  48 = +B
keycode  49 = +p
	shift keycode  49 = +P
keycode  50 = +m
	shift keycode  50 = +M
```

Love Norman!

**Comment by deekayen** [comment]
Could you turn it into a pull request?

It seems odd to put in /usr/share/kbd/keymaps/i386/qwerty/norman.map.gz. Would it not work in something like /usr/share/kbd/keymaps/i386/norman/norman.map.gz?

**Comment by ALTinners** [comment]
Yeah can do.

Was unsure as to the schema for the folders there - looking in there i can see azerty and friends so your suggestion makes sense

**Comment by ALTinners** [comment]
https://github.com/deekayen/norman/pull/24
