### ISSUE TITLE
Add the website to this one (or its own one)

### ISSUE THREAD

**Issue by paulmakepeace** [deekayen/norman#26]
I was hoping to suggest an edit around installation but couldn't make a PR (it was to log in & out as a user on macOS to pick up the new keyboard). Would you be up for making the website available in GitHub?

**Comment by deekayen** [comment]
It's been a long time since the website has had an update, so I'm actually not 100% sure where I'm hosting it right now. I'm pretty sure it's github pages and you can do a PR against the gh-pages branch, and a merge would automatically publish. https://github.com/deekayen/norman/tree/gh-pages
