### ISSUE TITLE
Norman bundle on OS X mavericks breaks Ctrl key

### ISSUE THREAD

**Issue by amjith** [deekayen/norman#4]
I've installed the Norman bundle on OS X mavericks and when I have norman enabled and press Ctrl-A it outputs 'A'. But with the default qwerty it moves the cursor to the beginning of line. 

I've remapping it but anything with Ctrl+ 'Char' is completely ignored.

**Comment by abyx** [comment]
The fix in the commit that closes this does fix the issue, but it seems that the installer wasn't updated with this change. I had to manually download the layout file and install it.

**Comment by deekayen** [comment]
Yeah, I probably forgot to update the installer.

**Comment by deekayen** [comment]
I finally updated the installer - uploaded to https://normanlayout.info/files/Norman.dmg.
