### ISSUE TITLE
CTRL key combinations broken in MacVim

### ISSUE THREAD

**Issue by thehunmonkgroup** [deekayen/norman#8]
Not sure if this bug is due to Norman or MacVim, but it seemed most likely a Norman build issue, so filing here first.

Using any CTRL + key combination gives unexpected results in MacVim. The key combinations work fine in regular vim. I'd suspect this as a MacVim bug, but the issue does not occur when I switch to the Colemak layout.

The most clear example is ctrl+ww - switch between windows. In US or Colemak, this key combination works properly, but in Norman, it does not switch windows, but instead moves the cursor forward one word, more like the meta+w combination would in bash.

I used the Key Codes app to verify what codes get sent pressing ctrl+w in both US and Norman, and they are exactly the same. I also tried disabling the "Draw marked text inline" setting in MacVim, based on some searching around I did for a workaround on that end, but it didn't help.

Not really sure what to do next -- MacVim is my daily workspace, it's a deal-killer for me if I can't have the basic key combos working there.

Wondering if this might be related to #4?

**Comment by deekayen** [comment]
Try the new installer at https://normanlayout.info/files/Norman.dmg.
