### ISSUE TITLE
compare to white

### ISSUE THREAD

**Issue by pvinis** [deekayen/norman#9]
https://github.com/mw8/white_keyboard_layout

**Comment by deekayen** [comment]
The algorithms are interesting, but it doesn't account for some of Norman's primary benefits. Most in contrast is keeping letters on the same hands as much as possible to ease conversion from QWERTY. Shifting your right hand to the right one key is also a big deal. The close to the pitch to generate your own based on your own corpus also breaks standardization, so it's not really a White layout so much as the White layout generator.
